version: '3.4'
services:
  postgres:
    image: 'postgres:13-alpine'
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
    - POSTGRES_USER=etlflow
    - POSTGRES_PASSWORD=etlflow
    - POSTGRES_DB=etlflow
    ports:
    - '5432:5432'
  webserver:
    image: 'etlflow:0.11.0'
#    entrypoint: /opt/docker/bin/examples
#    command: run_db_migration
    deploy:
      resources:
        limits:
          memory: 2G
    restart: always
    depends_on:
     - postgres
    environment:
        LOG_DB_URL: 'jdbc:postgresql://postgres:5432/etlflow'
        LOG_DB_USER: etlflow
        LOG_DB_PWD: etlflow
        LOG_DB_DRIVER: org.postgresql.Driver
    ports:
    - '8080:8080'
  prometheus:
    image: 'prom/prometheus'
    restart: always
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
    - '9090:9090'
  grafana:
      image: "grafana/grafana"
      environment:
        GF_SECURITY_ADMIN_PASSWORD: admin
      ports:
      - "3000:3000"
